2022-12-14 11:54:59,779 INFO     [base.py:166] Scheduler started
2022-12-14 11:56:17,247 INFO     [updater.py:863] Received signal 2 (SIGINT), stopping...
2022-12-14 11:56:17,248 INFO     [base.py:198] Scheduler has been shut down
2022-12-14 11:56:17,459 WARNING  [updater.py:874] Exiting immediately!
2022-12-14 11:56:19,048 INFO     [simple_echo.py:22] Бот стартовал
2022-12-14 11:56:19,049 INFO     [base.py:166] Scheduler started
2022-12-14 11:57:34,263 INFO     [updater.py:863] Received signal 2 (SIGINT), stopping...
2022-12-14 11:57:34,273 INFO     [base.py:198] Scheduler has been shut down
2022-12-14 11:57:34,483 WARNING  [updater.py:874] Exiting immediately!
2022-12-14 11:57:36,280 INFO     [simple_echo.py:22] Бот стартовал
2022-12-14 11:59:13,779 INFO     [simple_echo.py:22] Бот стартовал
2022-12-14 11:59:13,779 INFO     [base.py:166] Scheduler started
2022-12-14 12:03:41,483 INFO     [updater.py:863] Received signal 2 (SIGINT), stopping...
2022-12-14 12:03:41,484 INFO     [base.py:198] Scheduler has been shut down
2022-12-14 12:03:43,673 WARNING  [updater.py:874] Exiting immediately!
2022-12-14 12:03:46,828 INFO     [simple_echo.py:28] Бот стартовал
2022-12-14 12:03:46,829 INFO     [base.py:166] Scheduler started
2022-12-14 12:05:27,764 INFO     [updater.py:863] Received signal 2 (SIGINT), stopping...
2022-12-14 12:05:27,770 INFO     [base.py:198] Scheduler has been shut down
2022-12-14 12:05:28,161 WARNING  [updater.py:874] Exiting immediately!
2022-12-14 12:05:30,420 INFO     [simple_echo.py:31] Бот стартовал
2022-12-14 12:05:30,420 INFO     [base.py:166] Scheduler started
2022-12-14 12:05:38,507 INFO     [simple_echo.py:20] We have just echoed: "ул"
2022-12-14 12:05:39,616 INFO     [simple_echo.py:20] We have just echoed: "ля"
2022-12-14 12:05:40,475 INFO     [simple_echo.py:20] We have just echoed: "ля"
2022-12-14 12:05:41,803 INFO     [simple_echo.py:20] We have just echoed: "фа"
2022-12-14 12:05:42,918 INFO     [simple_echo.py:20] We have just echoed: "витя"
2022-12-14 12:05:44,993 INFO     [simple_echo.py:20] We have just echoed: "кертанов"
2022-12-14 12:07:51,764 INFO     [updater.py:863] Received signal 2 (SIGINT), stopping...
2022-12-14 12:07:51,765 INFO     [base.py:198] Scheduler has been shut down
2022-12-14 12:07:52,508 WARNING  [updater.py:874] Exiting immediately!
2022-12-14 12:07:54,375 INFO     [simple_echo.py:31] Бот стартовал
2022-12-14 12:07:54,376 INFO     [base.py:166] Scheduler started
2022-12-14 12:08:05,483 ERROR    [dispatcher.py:821] No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/viktorkertanov/projects/geo_bot/env/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 557, in process_update
    handler.handle_update(update, self, check, context)
  File "/Users/viktorkertanov/projects/geo_bot/env/lib/python3.10/site-packages/telegram/ext/handler.py", line 199, in handle_update
    return self.callback(update, context)
  File "/Users/viktorkertanov/projects/geo_bot/simple_echo.py", line 16, in talk_to_me
    text_to_repeat = update.message.text
AttributeError: 'NoneType' object has no attribute 'text'
2022-12-14 12:08:06,454 INFO     [simple_echo.py:20] We have just echoed: "d"
2022-12-14 12:08:08,469 INFO     [simple_echo.py:20] We have just echoed: "ул"
2022-12-14 12:08:09,260 INFO     [simple_echo.py:20] We have just echoed: "ля"
2022-12-14 12:08:10,227 INFO     [simple_echo.py:20] We have just echoed: "ля"
2022-12-14 12:08:58,471 INFO     [simple_echo.py:20] We have just echoed: "Как дела?"
2022-12-14 12:17:54,762 INFO     [updater.py:863] Received signal 2 (SIGINT), stopping...
2022-12-14 12:17:54,774 INFO     [base.py:198] Scheduler has been shut down
2022-12-14 12:17:56,071 WARNING  [updater.py:874] Exiting immediately!
